matrix:
  include:
    - language: rust
      sudo: required
      dist: xenial
      cache: cargo
      rust:
        - stable
        - nightly

      before_script:
      - rustup component add rustfmt

      before_cache:
      - cargo install cargo-tarpaulin -f

      script:
      - cargo clean
      - cargo fmt --all -- --check
      - cargo build
      - cargo test

      after_success: |
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)

    - language: node_js
      sudo: false
      os: linux
      env: BUILDTYPE=release
      node_js: 10

      cache:
        directories:
        - $HOME/.cargo
        - $TRAVIS_BUILD_DIR/native/target

      install:
        - node -v
        - which node
        - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
        - sh /tmp/rustup.sh -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - source "$HOME/.cargo/env"
        - yarn install --ignore-scripts
        - neon clean
        - neon build $([ "${BUILDTYPE}" == 'debug' ] && echo "" || echo "--release")

      script:
        - yarn coverage

      after_success:
        - ./scripts/publish.sh --debug=$([ "${BUILDTYPE}" == 'debug' ] && echo "true" || echo "false")

    - language: node_js
      sudo: false
      os: osx
      osx_image: xcode9.2
      env: BUILDTYPE=release
      node_js: 10

      cache:
        directories:
        - $HOME/.cargo
        - $TRAVIS_BUILD_DIR/native/target

      install:
        - node -v
        - which node
        - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
        - sh /tmp/rustup.sh -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - source "$HOME/.cargo/env"
        - yarn install --ignore-scripts
        - neon clean
        - neon build $([ "${BUILDTYPE}" == 'debug' ] && echo "" || echo "--release")

      script:
        - yarn test

      after_success:
        - ./scripts/publish.sh --debug=$([ "${BUILDTYPE}" == 'debug' ] && echo "true" || echo "false")
